# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3c6d8e44f89a909f6d4077e2eecd75ae9be52958abe1fbdcaf09226a549232a69f3b17661065181be37297cf419624bc79901aa705b358390f03e0ffa457d41

test:
  secret_key_base: 499de8c729f07dd7624c0893db68674a9da89591e31d85d4d8ab537f916424236c7c9273672462d3957eaca7842fcd71bca3a8a5a09f044e4900a4c3d8ab67c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
